my:
  message: Hello Greeting
  name: My App
  description: Welcomen to ${app.name}
  list:
       values: One,Two,Three

db:
  connection: "{connectionString:'http://_____', userName:'Admin',password: 'pass'}"
  host: 127.0.0.1
  port: 3306

management.endpoints.web.exposure.include: "*"
#spring.profiles.active: test

spring.config.import: "optional:configserver:"

spring.cloud.config.uri: http://localhost:8888

spring.application.name: spring-boot-config